In [27]:
import numpy as np
from load_mtx import load_mtx

A, b = load_mtx("tasks/1_1.txt")
n = len(b)

A, b

(array([[ 1., -5., -7.,  1.],
        [ 1., -3., -9., -4.],
        [-2.,  4.,  2.,  1.],
        [-9.,  9.,  5.,  3.]]),
 array([-75., -41.,  18.,  29.]))

In [28]:
# Permutations для строк в матрице
P = np.eye(n, dtype=float)

L = np.eye(n, dtype=float)
U = A.copy()

for col in range(n):
    pivot_row = col + np.argmax(np.abs(U[col:, col]))

    if np.isclose(U[pivot_row, col], 0.0):
        raise ValueError("Матрица вырожденная: LU-разложение невозможно")

    if pivot_row != col:
        U[[col, pivot_row], :] = U[[pivot_row, col], :]
        P[[col, pivot_row], :] = P[[pivot_row, col], :]

        L[[col, pivot_row], :col] = L[[pivot_row, col], :col]

    for row in range(col + 1, n):
        factor = U[row, col] / U[col, col]
        L[row, col] = factor
        U[row, col:] -= factor * U[col, col:]

U, L

(array([[-9.        ,  9.        ,  5.        ,  3.        ],
        [ 0.        , -4.        , -6.44444444,  1.33333333],
        [ 0.        ,  0.        , -5.22222222, -4.33333333],
        [ 0.        ,  0.        ,  0.        ,  2.93617021]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [-0.11111111,  1.        ,  0.        ,  0.        ],
        [-0.11111111,  0.5       ,  1.        ,  0.        ],
        [ 0.22222222, -0.5       ,  0.44680851,  1.        ]]))

In [29]:
from IPython.display import display, Math

pb = P @ b

y = np.zeros(n, dtype=float)
for row in range(n):
    y[row] = pb[row] - np.dot(L[row, :row], y[:row])

x = np.zeros(n, dtype=float)
for row in range(n - 1, -1, -1):
    s = np.dot(U[row, row + 1:], x[row + 1:])
    x[row] = (y[row] - s) / U[row, row]

for i in range(n):
    display(Math(fr"x_{i+1} = {x[i]:.3f}"))

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

Проверка решения

In [30]:
np.allclose(x, np.linalg.solve(A, b))

True

Проверка корректности матриц L U и перестановки строк

In [31]:
np.allclose(A, P.T @ L @ U)

True